import os 
import numpy as np 
from PIL import Image 
import cv2 
from tqdm import tqdm
import xml.etree.ElementTree as ET

# Import for SMOTE
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from keras.preprocessing.image import array_to_img, img_to_array,load_img
from keras.src.legacy.preprocessing.image import ImageDataGenerator

# keras imports for building our neural network
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

## smote_images.py stores augmented IMAGES in augmented_images dir

PIXEL_HORIZONTAL = 512
PIXEL_VERTICAL = 512

def read_images(image_dir):
    images = []
    labels = []
    for image_name in tqdm(os.listdir(image_dir)):
        image_full_path = os.path.join(image_dir, image_name)
        image = cv2.imread(image_full_path)
        image = resize(image)
        images.append(image)
        labels.append(get_label_for_image(image_name))
    return np.array(images), np.array(labels)

def resize(image):
    resized = cv2.resize(image, (PIXEL_HORIZONTAL, PIXEL_VERTICAL))
    return resized

def get_augmented_image_dir(dir_name='images'):
    current = os.path.dirname(os.path.abspath(__file__))  
    image_dir = os.path.join(current, "../", dir_name)
    return image_dir

def get_label_for_image(image_name):
    label_dir = get_augmented_image_dir('annotations')
    label_file_name = image_name.replace('.png', '.xml')
    label_full_path = os.path.join(label_dir, label_file_name)
    return read_label_from_xml(label_full_path)

# LABELS
def read_label_from_xml(label_xml_filename):
    tree = ET.parse(label_xml_filename)
    root = tree.getroot()
    return root[4][0].text 

def augment_images():
    # Augment images and save them in a different folder
    X_train, y = read_images(get_augmented_image_dir())
    #print(X_train.shape)
    #print(y.shape)
    X_train = np.reshape(X_train, (877, PIXEL_HORIZONTAL * PIXEL_VERTICAL * 3))

    sm = SMOTE(random_state=2)
    X_smote, y_smote = sm.fit_resample(X_train, y)

    #Retrieve the image and save it to drive. Here's an example for a single image
    #print(X_smote.shape)
    Xsmote_img=X_smote.reshape(2608, PIXEL_HORIZONTAL, PIXEL_VERTICAL, 3)

    #Save all images generated by the SMOTE method to the drive

    train_sep_dir='/Users/pankajyawale/projects/college_impact/Road-Sign-Detection/augmented_images/'

    for i in range(len(Xsmote_img)):
        label=y_smote[i]
        if not os.path.exists(train_sep_dir + str(label)):
            os.mkdir(train_sep_dir + str(label))
        aug_img = array_to_img(Xsmote_img[i]* 255)
        aug_img.save(train_sep_dir + str(label) + '_'+ str(i) + '.jpg')



def main():
    augment_images()

if __name__ == '__main__':
    main()

